### ISSUE TITLE
Add support in CubeSat constructor for loading the shape from an STL file

### ISSUE THREAD

**Issue by queens-satellite-team** [queens-satellite-team/attitude-control-simulator#1]
Currently the `CubeSat` class is instantiated by:
```
sat = CubeSat('3U', position, orientation)
```
where `position` and `orientation` are vectors. The `CubeSat` class uses the `3U` string to add an instance of the `Shape` class as a property. We would like the constructor for `CubeSat` to be overloaded so that it would be possible to:
```
sat = CubeSat('3U', position, orientation, pathToStl)
```
where `pathToStl` is the path to an STL file. There is already a function in the `Util` package called `Stl2Patch` that converts STL files to the faces and vertices arrays that MATLAB recognizes for rendering with `Patch`. Remember to develop/branch off of the `develop` branch not `master`.

**Comment by anthonysteel** [comment]
You will want to look into `varargin` which is the [variable-length input argument list in MATLAB](https://www.mathworks.com/help/matlab/ref/varargin.html). This because there will now be a variable length that the input arguments can be (either 3 in the case of `CubeSat('3U', position, orientation)` or 4 `CubeSat('3U', position, orientation, pathToStl)`). `varargin` is a cell which means that you access its elements using the brace syntax. For example, `varargin{1}` would return `3U`. So you need to have an `if` statement which checks for the length of `varargin` and then accesses the last element, calls the `Util.Stl2Patch` function and then calls it on the `pathStlPath`.
